name: powerdns
services:
  pdns-admin:
    container_name: pdns-admin
    image: pschiffe/pdns-admin:0.4.1
    ports:
      - target: 80
        published: ${WEBUI_PORT:-8080}
        protocol: tcp
    restart: unless-stopped
    environment:
      PDNS_ADMIN_SQLA_DB_HOST: mariadb
      PDNS_ADMIN_SQLA_DB_PORT: 3306
      PDNS_ADMIN_SQLA_DB_USER: root
      PDNS_ADMIN_SQLA_DB_PASSWORD: pdns
      PDNS_ADMIN_SQLA_DB_NAME: pdns
    networks:
      powerdns-backend:
      powerdns-frontend:
    depends_on:
      - mariadb
  mariadb:
    container_name: mariadb
    image: mariadb:12.1.1-ubi10-rc
    environment:
      MARIADB_ROOT_PASSWORD: pdns
      MARIADB_DATABASE: pdns
    ports:
      - target: 3306
        published: "3306"
        protocol: tcp
    restart: unless-stopped
    networks:
      - powerdns-backend
networks:
  powerdns-backend:
  powerdns-frontend:
    driver: bridge
x-casaos:
  envs:
    - container: PDNS_ADMIN_SQLA_DB_HOST
      description:
        en_us: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
  architectures:
    - amd64
    - "386"
    - arm64
    - arm
  main: pdns-admin
  author: daymickcorr
  title: 
    en_us: PowerDNS
  description:
    en_us: powerdns
  tagline: 
    en_us: powerdns
  index: /
  port_map: ${WEBUI_PORT:-8080}
  