name: powerdns
services:
  pdns-admin:
    image: pschiffe/pdns-admin:0.4.1
    network_mode: bridge
    ports:
      - target: 80
        published: ${WEBUI_PORT:-8080}
        protocol: tcp
    restart: unless-stopped
    environment:
      PDNS_ADMIN_SQLA_DB_HOST: mysql
      PDNS_ADMIN_SQLA_DB_PORT: 3306
      PDNS_ADMIN_SQLA_DB_USER: root
      PDNS_ADMIN_SQLA_DB_PASSWORD: powerdnsadmin
      PDNS_ADMIN_SQLA_DB_NAME: powerdnsadmin

x-casaos:
  envs:
    - container: PDNS_ADMIN_SQLA_DB_HOST
      description:
        en_us: Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
  architectures:
    - amd64
    - "386"
    - arm64
    - arm
  main: pdns-admin
  author: daymickcorr
  title: 
    en_us: PowerDNS
  description:
    en_us: powerdns
  tagline: 
    en_us: powerdns
  index: /
  port_map: ${WEBUI_PORT:-8080}
  