name: powerdns
services:
  pdns-admin:
    image: pschiffe/pdns-admin:0.4.1
    network_mode: bridge
    ports:
      - target: 80
        published: ${WEBUI_PORT}
        protocol: tcp
    restart: unless-stopped
    x-casaos:
      index: /
      port_map: ${WEBUI_PORT}

x-casaos:
  architectures:
    - amd64
    - "386"
    - arm64
    - arm
  main: powerdns
  author: daymickcorr
  title: 
    en_us: PowerDNS
  